# Volcano plots - GSVA - Between passages, Day 3, Hallmarks, highlighted

```{r}
#| include: False
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)
```

```{r}
#| include: False
here::i_am("quarto/04-volcano3D-gsva.qmd")

# Load packages
library(GSVA)
library(here)
library(tidyverse)
library(volcano3D)

# Load data for plotting
polar_manual_gsva <- readRDS(
  file <- here::here(
    "output",
    "data_enrichment",
    "GSVA",
    "polar_manual_gsva.RDS"
  )
)
```

```{r}
#| include: False
# Define plot specs
breaks_r <- seq(
  from = 0.5,
  to = 2.5,
  by = 1
)

breaks_z <- seq(
  from = 0,
  to = 40,
  by = 10
)

camera <- list(
  x = -1.05,
  y = 0.9,
  z = 0.375
)
```

## 3D volcano plot (P+7)
```{r}
#| include: False
volcano3d <- map(
  polar_manual_gsva[1],
  \(polar_manual) {
    volcano3D(
      polar_manual,
      type = 1,
      label_rows = c(
        "HALLMARK_TNFA_SIGNALING_VIA_NFKB",
        "HALLMARK_TGF_BETA_SIGNALING",
        "HALLMARK_KRAS_SIGNALING_UP",
        "HALLMARK_HYPOXIA"
      ),
      grid_options = list(
        r_axis_ticks = breaks_r,
        z_axis_ticks = breaks_z
      ),
      label_size = 24,
      z_axis_title_size = 12,
      radial_axis_title_size = 12,
      camera_eye = camera
    )
  }
)
```

```{r}
volcano3d[[1]]
```


## 3D volcano plot (P+7)
```{r}
#| include: False
volcano3d <- map(
  polar_manual_gsva[1],
  \(polar_manual) {
    volcano3D(
      polar_manual,
      type = 1,
      label_rows = c(
        "HALLMARK_INTERFERON_ALPHA_RESPONSE",
        "HALLMARK_INTERFERON_GAMMA_RESPONSE",
        "HALLMARK_G2M_CHECKPOINT",
        "HALLMARK_MYC_TARGETS_V2"
      ),
      grid_options = list(
        r_axis_ticks = breaks_r,
        z_axis_ticks = breaks_z
      ),
      label_size = 24,
      z_axis_title_size = 12,
      radial_axis_title_size = 12,
      camera_eye = camera
    )
  }
)
```

```{r}
volcano3d[[1]]
```

